name: Latest blog posts

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: 'https://www.fantajin.com/feed.xml'
          max_post_count: 5
          commit_message: 'Chore : README 최신 블로그 글 갱신'
